name: MonoGS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  # - torchaudio=0.12.0
  # - torchvision=0.13.0
  - tqdm
  - pip:
    - -e /home/uu/Downloads/torch-cu-conda/torch-1.12.0+cu113-cp37-cp37m-linux_x86_64.whl
    - submodules/simple-knn
    - submodules/diff-gaussian-rasterization
    - opencv-python==4.8.1.78
    - munch
    - trimesh
    - evo==1.11.0
    - open3d==0.17.0
    - torchmetrics
    - imgviz
    - PyOpenGL
    - glfw
    - PyGLM
    - wandb
    - lpips
    - rich
    - ruff